### ISSUE TITLE
Add metric for skipped certs per client

### ISSUE THREAD

**Issue by goliel** [d-Rickyy-b/certstream-server-go#34]
Hi,
We have migrated our certstream server from calidog's to this one and have been enjoying the added logs and metrics.
We had an issue with our consumer being too slow and certs being skipped, we have since fixed this issue but we would like to monitor it.

Right now we only monitor at the log level, Adding metric for the skipped amount would help us follow this issue better.

**Comment by d-Rickyy-b** [comment]
When using a reverse proxy before certstream-server-go, there's now way to get the actual port that's being used by a client. Currently, the metric used is showing up as IP:Port. But I am currently improving the parsing of the X-Real-IP and similar headers so that we get the actual IP instead of the reverse proxy's IP address. That means that the metric will be changed to only IP.

If you have any better idea on how to name the metric, please let me know.
